:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_preprocessor_directives: FALSE
  :generate_deep_dependencies: FALSE
  :use_auxiliary_dependencies: FALSE
  :use_deep_dependencies: FALSE
  :auto_link_deep_dependencies: FALSE
  :build_root: unittests/build
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

:paths:
  :test:
    - +:unittests/test/**
    - -:unittests/test/support
  :source:
    - src/
  :support:
    - unittests/test/support
  :include:
    - ./
    - inc/
    - driver/inc
    - driver/hal

:environment:

:extension:
  :executable: .out
  
:defines:
  :common: &common_defines
    - __STATIC_INLINE="static inline"
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :ignore
  :enforce_strict_ordering: TRUE
  :includes_h_pre_orig_header:
    - unittest/test/support/
  :plugins:
    - :ignore
    - :ignore_arg
    - :callback
    - :expect_any_args
    - :return_thru_ptr
  :treat_inlines: :include
  :inline_function_patterns:
   - 'static inline'
   - '__STATIC_INLINE'

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_gtestlike_tests_report
